name: UltraPedestrian
favicon: null
layout_spectrum: 0.63804
typography_spectrum: 0.57945
title: >-
  Trail running - Ultrarunning - Fastpacking - Thru-hiking - Supported -
  Unsupported - Self-supported - All of the Above
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00934c'
    - '#ffcf54'
    - '#f01927'
    - '#100708'
    - '#f8753d'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.8631533882580698
  rhythmicContrast: 0
purpose: []
