name: UltraPedestrian
favicon: null
layout_spectrum: 0.5469823845196515
typography_spectrum: 0.14280038326978683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6857062159106135
  lightness: 0.20060026017017663
  saturation: 0.8631533882580698
  rhythmicContrast: 0.5400821899529546
purpose: []
